spring:
  cloud:
    gateway:
      routes:
        - id: baidu-rout
          uri: https://www.baidu.com
          predicates:
            - Query=url,baidu

        - id: qq-rout
          uri: https://www.qq.com
          predicates:
            - Query=url,qq