server:
  port: 11000
spring:
  application:
    name: mall-ware
  datasource:
    username: martinyuyy
    password: qwer2580.0
    url: jdbc:mysql://106.13.53.40:3306/mall_wms
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 106.13.53.40:8848


mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
